### ISSUE TITLE
El codigo

### ISSUE THREAD

**Issue by reina-vergara** [reina-vergara/Software2#1]
No pueden ver el codigo

**Comment by reina-vergara** [comment]
[Sistema_Ferreteria_V_0.0.2.zip](https://github.com/reina-vergara/Software2/files/2065493/Sistema_Ferreteria_V_0.0.2.zip)
Descarguenlo  para que todos tengan

**Comment by SimoneLanza** [comment]
yo tampoco puedo ver el codigo :/
